FROM dictybase/modware-loader:devel
MAINTAINER Siddhartha Basu<siddhartha-basu@northwestern.edu>

COPY run.sh /usr/src/modware-loader/
RUN chmod u+x /usr/src/modware-loader/run.sh
CMD ["/usr/src/modware-loader/run.sh"]
