version: '3.2'
services:
    dsc:
        image: dictybase/migration-data-export
        volumes:
            - data:/data
            - config:/config
            - log:/log
        env_file:
            - ./common.env
        command: "app dsc-annotations && app dsc-users"
